[phases.setup]
nixPkgs = [
  "php84",
  "composer",
  "nodejs_22"
]

[phases.install]
cmds = [
  "composer install --ignore-platform-reqs"
]

[phases.build]
cmds = [
  "npm install",
  "npm run build"
]
